# browser=chrome
# storefront_url=https://demo.opencart.com/
# admin_url=https://demo.opencart.com/admin/
# timeout=15

browser=chrome
storefront_url=https://tutorialsninja.com/demo/
admin_url=https://tutorialsninja.com/demo/admin/
timeout=15